### ISSUE TITLE
does not have a parametrization on weight

### ISSUE THREAD

**Issue by five-f** [douhaohaode/xtts_v2#3]
请问有遇到这个问题吗：
File "D:\anaconda\envs\py39\lib\site-packages\torch\nn\utils\parametrize.py", line 633, in remove_parametrizations
    raise ValueError(f"Module {module} does not have a parametrization on {tensor_name}")
ValueError: Module Conv1d(1024, 512, kernel_size=(7,), stride=(1,), padding=(3,)) does not have a parametrization on weight

**Comment by douhaohaode** [comment]
十分抱歉， 我在使用时未遇到这个错误

**Comment by five-f** [comment]
> 十分抱歉， 我在使用时未遇到这个错误
好的谢谢！
